# This file was generated by GoReleaser. DO NOT EDIT.
cask "es" do
  name "es"
  desc ""
  homepage ""
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "es"

  on_macos do
    on_intel do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_darwin_amd64.tar.gz"
      sha256 "32b06216b7d717993d554f3267ea95f69619e9b1a6d25c71b8dd213c745263ad"
    end
    on_arm do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_darwin_arm64.tar.gz"
      sha256 "c5353b938e20364042ac1ebeaf934c235131de44bdb27755e159ee5d717fe018"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_linux_amd64.tar.gz"
      sha256 "8ac4bc591ede4a683d7a1b5a3cea8b5237d1e764d9ac1d4af3c1d983f9d127f0"
    end
    on_arm do
      url "https://github.com/zmoog/es/releases/download/v#{version}/es_#{version}_linux_arm64.tar.gz"
      sha256 "4e34ce47ad5afa8efb2f9d7bb33dacff99e5e20b4f396c761ea30aa9ffbc13dc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/es"]
    end
  end

  # No zap stanza required
end
